# Site settings
title: Bryan Braun - Student of Life
email: bbraun7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
logo: /assets/images/logo.png
url: https://www.bryanbraun.com # the base hostname & protocol for your site, e.g. http://example.com
author: Bryan Braun
repository: bryanbraun/bryanbraun.github.io
timezone: America/New_York
host: 0.0.0.0 # This lets us test on devices locally. See http://stackoverflow.com/a/16608698/1154642
github:
  url: http://localhost:4000 # this gets overridden when the site is deployed on github pages
feed:
  path: rss.xml # preserve the name of my Drupal RSS feed b/c I can, and it's possible that some people are still subscribed to it.

# Build settings
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/_sass
  style: compressed
include: ["_pages"]
# See HTML compression settings at http://jch.penibelst.de/#configuration
#   Don't use inline javascript slash-comments with this enabled (`//`), or you'll
#   see JS errors. See other caveauts here: http://jch.penibelst.de/#restrictions
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
  ignore:
    envs: []
  blanklines: false
  profile: false

# Content settings
permalink: pretty
collections:
- books
defaults:
  -
    scope:
      path: ""      # all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      comments: true
      layout: post


# Custom Vars
branch: master      # the branch my live site is deployed to.
