# Site settings
title: Bryan Braun - Student of Life
email: bbraun7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
logo: /assets/images/logo.png
url: http://bryanbraun.com # the base hostname & protocol for your site, e.g. http://example.com
repository: bryanbraun/bryanbraun.github.io
timezone: America/New_York
github:
  url: http://localhost:4000 # this gets overridden when the site is deployed on github pages


# Build settings
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/_sass
  style: expanded


# Content settings
permalink: pretty
collections:
- books
defaults:
  -
    scope:
      path: ""      # all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      comments: true
      layout: post


# Custom Vars
branch: master      # the branch my live site is deployed to.
